[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = true
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.production]
src = "src"
out = "out"
libs = ["lib"]
ffi = false
solc = "0.8.28"
optimizer = true
optimizer_runs = 1000
via_ir = true
bytecode_hash = "none"

[profile.ci]
src = "src"
out = "out"
libs = ["lib"] 
ffi = false
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
